account: username

password:
  service_name: thu-auth

devices:
  - 192.168.1.100
  - 192.168.1.101

config:
  requests_timeout: 2
  monitor_interval: 60
  allow_webvpn: true
  allow_force_attempt: false
  force_attempt_interval: 600
